### PR TITLE
Combine sum type constructors

### PR DESCRIPTION
**Pull request by NavidJalali**
An attempt at fixing https://github.com/zio/zio-parser/issues/66

Caveats:
- For scala 3 now it uses a macro.
- For scala 2 it somehow does not need a class tag to call widen when using wildcards and it just works (????)
- Type inference for scala 2 is kind of whack: If you do not annotate the type it will guess `SuperType with Product with Serializable` which means that if you dont explicitly annotate it you wont be able to pass SubType such that `SubType <:< SuperType` because there is no instance for `SubType <:< SuperType with Product With Serializable` :( 
- It is polymorphic over -In and +Out however I did not add a partially applied class for it, if you think it is nice to add I am happy to add one.

### CODE REVIEW

**Comment by kitlangton** [comment]
Amazing! But, if you're down, could you add a test? I fear that it compiles but will not work correctly due to the implementation of widen.

**Comment by NavidKJalali** [comment]
@kitlangton That was a good idea, it did reveal an issue. If you don't explicitly annotate it, it will widen to the strictest possible superclass.
Using my test example: 
`weekDaySyntax` has underlying type `Syntax[String, Char, Char, WeekDay with Product, WeekDay with Product]` if no type parameter is specified. It causes a compile time error if you try to parse a Weekday because it expects it to have Product with Serializable I guess. But if you force IntelliJ to derive the type it will figure out the right thing and work as expected. I am not sure how to move forward here. I don't know if it's possible to get around this issue. Maybe I can create some kind of machinery to strip Product with Serializable from types 🤔  Not even sure that's possible. Advice is appreciated

**Comment by kitlangton** [comment]
Oh, that's great! Nice test :D 
I think that's fine. The user definitely needs to input the right type, that's totally fine. I ran into much different and worse trouble when I poked around with this last. Thanks, Navid!

**Review by vigoo — APPROVED** [review]
Nice, thanks!

**Comment by vigoo** [comment]
Seems like you need to run a `scalafmtAll`, and also something is wrong with it on Scala 3 :(

**Comment by NavidKJalali** [comment]
The problem seems to be that scala 3 cannot find the ClassTags for the wildcard types. I have really only two solutions for this. Both are kind of bad. 

1. Have 23 different versions of this function and use different type parameters that way you can specify both the type bound as well as the context bounds individually. I really hate this solution.
2. Bundle the syntax with the ClassTags in some kind of type and use implicit conversion at the call site to create the bundle. This is also kind of bad. The signature is not obvious and people might try to create them manually. It would look something like this:
image

What do you think?

**Comment by kitlangton** [comment]
I think the Scala 3 version might best be handled by a macro that rewrites it to the original syntax. I can give that a whirl (unless of course you want to 😄)

**Comment by NavidKJalali** [comment]
@kitlangton Oooh spicy 🌶. I'd like to see how that's done. I can certainly try but me no good at macros :(

**Comment by kitlangton** [comment]
Happy to pair on it if you're down? Perhaps we can stream the effort :D

**Comment by NavidKJalali** [comment]
I am definitely down!

**Comment by kitlangton** [comment]
Lovely! I'll reach out on discord to find a time :)

**Pull request merged**
